name: ps2
description: |
  http://ps2online.com/pes6/register/?fbclid=IwAR2XWmEhYEDsxwwBRB7_VD-Uby6zawt-rW_FqzPG_C80-JOujWGGpuOILN4
  Serial PC: ESWV4EFNTPK63XVTATEF
  Serial PS2: AAAAAAAAAAAAAAAAAAAA
status: development